<a href="https://colab.research.google.com/github/andilugo/Evaluacion/blob/main/Evaluaci%C3%B3n_Parte1_M%C3%A9xico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Evaluación Parte1 México
Andrea Cosset Hernández Lugo A01707744

In [ ]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Carga desde un archivo .csv
mex= pd.read_csv('DF_Mexico.csv')
mex.head(5)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2056638,https://www.airbnb.com/rooms/2056638,20230329041210,2023-03-30,city scrape,Amplio y luminoso loft en Coyoacán,Cómodo loft de dos pisos magníficamente ubicad...,NaN,https://a0.muscache.com/pictures/28353712/4379...,10531228,...,4.95,5.00,4.86,NaN,f,3,3,0,0,0.19
1,2072354,https://www.airbnb.com/rooms/2072354,20230329041210,2023-03-30,city scrape,Coyoacan Historic Studio Apartment,This studio flat is adjacent to the owner's ho...,"Located in Coyoacan, in a quiet neighborhood w...",https://a0.muscache.com/pictures/369f3371-593a...,16840050,...,5.00,4.95,4.84,NaN,f,2,2,0,0,0.54
2,696037,https://www.airbnb.com/rooms/696037,20230329041210,2023-03-29,city scrape,"3 Bedrooms, 2 blocks from Polanco - ALL RENOVA...","Beautifully decorated 3 bedroom apartment, it ...","This area is called Nuevo Polanco, it has bein...",https://a0.muscache.com/pictures/10960397/67b2...,3531879,...,4.92,4.58,4.71,NaN,f,3,3,0,0,0.31
3,35797,https://www.airbnb.com/rooms/35797,20230329041210,2023-03-29,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Centro comercial Santa Fe, parque interlomas y...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
4,44616,https://www.airbnb.com/rooms/44616,20230329041210,2023-03-30,city scrape,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,4.78,4.98,4.48,NaN,f,12,3,2,0,0.46

In [ ]:
#Identificar valores nulos por columna
valores_nulos=mex.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               3596
Length: 75, dtype: int64

In [ ]:
valores_nulos.to_csv("valores_nulos.csv")

In [ ]:
#Identificar valores nulos por dataframe
valores_nulostot=mex.isnull().sum().sum()
valores_nulostot

189609

In [ ]:
#Elimino columnas que tienen todas las filas vacías
mex.drop(["neighbourhood_group_cleansed", "bathrooms", "calendar_updated"], axis=1)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2056638,https://www.airbnb.com/rooms/2056638,20230329041210,2023-03-30,city scrape,Amplio y luminoso loft en Coyoacán,Cómodo loft de dos pisos magníficamente ubicad...,NaN,https://a0.muscache.com/pictures/28353712/4379...,10531228,...,4.95,5.00,4.86,NaN,f,3,3,0,0,0.19
1,2072354,https://www.airbnb.com/rooms/2072354,20230329041210,2023-03-30,city scrape,Coyoacan Historic Studio Apartment,This studio flat is adjacent to the owner's ho...,"Located in Coyoacan, in a quiet neighborhood w...",https://a0.muscache.com/pictures/369f3371-593a...,16840050,...,5.00,4.95,4.84,NaN,f,2,2,0,0,0.54
2,696037,https://www.airbnb.com/rooms/696037,20230329041210,2023-03-29,city scrape,"3 Bedrooms, 2 blocks from Polanco - ALL RENOVA...","Beautifully decorated 3 bedroom apartment, it ...","This area is called Nuevo Polanco, it has bein...",https://a0.muscache.com/pictures/10960397/67b2...,3531879,...,4.92,4.58,4.71,NaN,f,3,3,0,0,0.31
3,35797,https://www.airbnb.com/rooms/35797,20230329041210,2023-03-29,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Centro comercial Santa Fe, parque interlomas y...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
4,44616,https://www.airbnb.com/rooms/44616,20230329041210,2023-03-30,city scrape,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,4.78,4.98,4.48,NaN,f,12,3,2,0,0.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,853923589855678923,https://www.airbnb.com/rooms/853923589855678923,20230329041210,2023-03-30,city scrape,Rincón Mexico lindo!,Este lugar tiene una ubicación estratégica: ll...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,488030249,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
24220,853966732274073000,https://www.airbnb.com/rooms/853966732274073000,20230329041210,2023-03-29,city scrape,Departamento en zona diamante.,"Ubicado en zona diamante, junto al aeropuerto,...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,506816029,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
24221,854225071295768399,https://www.airbnb.com/rooms/854225071295768399,20230329041210,2023-03-29,city scrape,Habitación privada en magnífica casa,Relájate en este espacio muy tranquilo y elega...,NaN,https://a0.muscache.com/pictures/db71951a-8696...,154670560,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
24222,854247693069190865,https://www.airbnb.com/rooms/854247693069190865,20230329041210,2023-03-30,city scrape,Espacioso y luminoso loft - Roma,What else does it come with?<br />- WIFI 100MB...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7799414,...,NaN,NaN,NaN,NaN,t,13,13,0,0,NaN
24223,854260329845513725,https://www.airbnb.com/rooms/854260329845513725,20230329041210,2023-03-30,city scrape,Maravilloso departamento en Ciudad de México,Ven a descubrir este increíble departamento en...,Una zona muy bonita ya que varias de las atrac...,https://a0.muscache.com/pictures/miso/Hosting-...,506864314,...,NaN,NaN,NaN,NaN,t,2,2,0,0,NaN

In [ ]:
#datos cualitativos
mex["description"] = mex["description"].fillna("--") 
mex["neiborhood_overview"] = mex["neighborhood_overview"].fillna("--")
mex["host_name"] = mex["host_name"].fillna("--")
mex["host_since"] = mex["host_since"].fillna("--")
mex["host_location"] = mex["host_location"].fillna("--")
mex["host_about"] = mex["host_about"].fillna("--")
mex["host_response_time"] = mex["host_response_time"].fillna("--")
mex["host_is_superhost"] = mex["host_is_superhost"].fillna("--")
mex["host_thumbnail_url"] = mex["host_thumbnail_url"].fillna("--")
mex["host_picture_url"] = mex["host_picture_url"].fillna("--")
mex["host_thumbnail_url"] = mex["host_thumbnail_url"].fillna("--")
mex["host_has_profile_pic"] = mex["host_has_profile_pic"].fillna("--")
mex["host_identity_verified"] = mex["host_identity_verified"].fillna("--")
mex["neighbourhood"] = mex["neighbourhood"].fillna("--")
mex["bathrooms_text"] = mex["bathrooms_text"].fillna("--")
mex["first_review"] = mex["first_review"].fillna("--")
mex["last_review"] = mex["last_review"].fillna("--")
mex["license"] = mex["license"].fillna("--")
mex["host_response_rate"] = mex["host_response_rate"].fillna("0%")
mex["host_acceptance_rate"] = mex["host_acceptance_rate"].fillna("0%")

In [ ]:
#datos cuantitativos remplazar por 0 
mex = mex.fillna(0)

In [ ]:
#Corroboramos valores nulos en las columnas
valores_nulos = mex.isnull().sum()
valores_nulos

id                                              0
listing_url                                     0
scrape_id                                       0
last_scraped                                    0
source                                          0
                                               ..
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
neiborhood_overview                             0
Length: 76, dtype: int64

In [ ]:
#Corroboramos valores nulos por dataframe
valores_nulos=mex.isnull().sum().sum()
valores_nulos

0

In [ ]:
#Instalamos librería para análisis de variables categóricas
!pip install funpymodeling

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: funpymodeling in /usr/local/lib/python3.10/dist-packages (0.1.7)
Requirement already satisfied: matplotlib<4.0.0,>=3.2.2 in /usr/local/lib/python3.10/dist-packages (from funpymodeling) (3.7.1)
Requirement already satisfied: seaborn<0.11.0,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from funpymodeling) (0.10.1)
Requirement already satisfied: sklearn<0.1,>=0.0 in /usr/local/lib/python3.10/dist-packages (from funpymodeling) (0.0.post4)
Requirement already satisfied: numpy<2.0.0,>=1.18.5 in /usr/local/lib/python3.10/dist-packages (from funpymodeling) (1.22.4)
Requirement already satisfied: pandas<2.0.0,>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from funpymodeling) (1.5.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (2.8.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (23.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (0.11.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (3.0.9)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (8.4.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (4.39.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (1.0.7)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.0.5->funpymodeling) (2022.7.1)
Requirement already satisfied: scipy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from seaborn<0.11.0,>=0.10.1->funpymodeling) (1.10.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib<4.0.0,>=3.2.2->funpymodeling) (1.16.0)

In [ ]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
from seaborn import load_dataset
import numpy as np
import matplotlib.pyplot as plt
from funpymodeling.exploratory import freq_tbl

In [ ]:
#Separamos temporalmente las columnas cualitativas para llevar a cabo la eliminación de outliers de las columnas cuantitativas
mex_cuanti=mex.drop(['id','listing_url','scrape_id','bedrooms','last_scraped','source','name','description', 'picture_url','host_id','host_url','host_name','host_since','host_location','host_about','host_response_time','host_response_rate','host_is_superhost', 'host_thumbnail_url','host_picture_url','host_neighbourhood','host_total_listings_count','host_verifications', 'host_has_profile_pic', 'host_identity_verified','neighbourhood','neighbourhood_cleansed','neighbourhood_group_cleansed','property_type','room_type','bathrooms_text','amenities','has_availability','calendar_last_scraped','first_review','last_review','license','instant_bookable',], axis=1)
mex_cuanti

,neighborhood_overview,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,beds,price,minimum_nights,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,neiborhood_overview
0,0,0%,3,19.353530,-99.162990,3,0.0,1.0,"$1,434.00",1,...,5.00,4.95,5.00,4.86,3,3,0,0,0.19,--
1,"Located in Coyoacan, in a quiet neighborhood w...",0%,3,19.353580,-99.169480,2,0.0,1.0,$830.00,3,...,4.93,5.00,4.95,4.84,2,2,0,0,0.54,"Located in Coyoacan, in a quiet neighborhood w..."
2,"This area is called Nuevo Polanco, it has bein...",90%,4,19.441800,-99.184020,6,0.0,3.0,"$1,469.00",24,...,4.92,4.92,4.58,4.71,3,3,0,0,0.31,"This area is called Nuevo Polanco, it has bein..."
3,"Centro comercial Santa Fe, parque interlomas y...",0%,1,19.382830,-99.271780,2,0.0,1.0,"$3,658.00",1,...,0.00,0.00,0.00,0.00,1,1,0,0,0.00,"Centro comercial Santa Fe, parque interlomas y..."
4,0,86%,16,19.411620,-99.177940,14,0.0,8.0,"$18,000.00",1,...,4.87,4.78,4.98,4.48,12,3,2,0,0.46,--
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,0,100%,3,19.396663,-99.148145,2,0.0,1.0,$760.00,3,...,0.00,0.00,0.00,0.00,2,2,0,0,0.00,--
24220,0,0%,1,19.392023,-99.118722,7,0.0,3.0,"$1,520.00",1,...,0.00,0.00,0.00,0.00,1,1,0,0,0.00,--
24221,0,96%,1,19.371088,-99.190186,2,0.0,1.0,$533.00,5,...,0.00,0.00,0.00,0.00,1,0,1,0,0.00,--
24222,0,100%,13,19.403792,-99.164978,2,0.0,1.0,"$1,200.00",1,...,0.00,0.00,0.00,0.00,13,13,0,0,0.00,--
24223,Una zona muy bonita ya que varias de las atrac...,100%,2,19.426283,-99.175603,6,0.0,3.0,"$1,720.00",1,...,0.00,0.00,0.00,0.00,2,2,0,0,0.00,Una zona muy bonita ya que varias de las atrac...

In [ ]:
mex_cuali=mex.drop(['host_response_rate'	,'host_acceptance_rate', 'host_listings_count', 'host_total_listings_count','latitude','longitude','accommodates','beds','price','minimum_nights','maximum_nights','minimum_minimum_nights','maximum_minimum_nights','minimum_maximum_nights','maximum_maximum_nights','minimum_nights_avg_ntm','maximum_nights_avg_ntm','availability_30','availability_60','availability_90','availability_365','number_of_reviews','number_of_reviews_ltm','number_of_reviews_l30d','review_scores_rating','review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value','calculated_host_listings_count','calculated_host_listings_count_entire_homes','calculated_host_listings_count_private_rooms','calculated_host_listings_count_shared_rooms','reviews_per_month', "neighborhood_overview"], axis=1)
mex_cuali

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,bedrooms,amenities,calendar_updated,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable,neiborhood_overview
0,2056638,https://www.airbnb.com/rooms/2056638,20230329041210,2023-03-30,city scrape,Amplio y luminoso loft en Coyoacán,Cómodo loft de dos pisos magníficamente ubicad...,https://a0.muscache.com/pictures/28353712/4379...,10531228,https://www.airbnb.com/users/show/10531228,...,1.0,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",0.0,t,2023-03-30,2014-01-03,2018-06-24,--,f,--
1,2072354,https://www.airbnb.com/rooms/2072354,20230329041210,2023-03-30,city scrape,Coyoacan Historic Studio Apartment,This studio flat is adjacent to the owner's ho...,https://a0.muscache.com/pictures/369f3371-593a...,16840050,https://www.airbnb.com/users/show/16840050,...,1.0,"[""Free street parking"", ""Cleaning products"", ""...",0.0,t,2023-03-30,2014-01-01,2022-11-04,--,f,"Located in Coyoacan, in a quiet neighborhood w..."
2,696037,https://www.airbnb.com/rooms/696037,20230329041210,2023-03-29,city scrape,"3 Bedrooms, 2 blocks from Polanco - ALL RENOVA...","Beautifully decorated 3 bedroom apartment, it ...",https://a0.muscache.com/pictures/10960397/67b2...,3531879,https://www.airbnb.com/users/show/3531879,...,3.0,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",0.0,t,2023-03-29,2012-10-31,2022-12-21,--,f,"This area is called Nuevo Polanco, it has bein..."
3,35797,https://www.airbnb.com/rooms/35797,20230329041210,2023-03-29,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,https://www.airbnb.com/users/show/153786,...,1.0,"[""Wifi"", ""Washer"", ""BBQ grill"", ""Indoor firepl...",0.0,t,2023-03-29,--,--,--,f,"Centro comercial Santa Fe, parque interlomas y..."
4,44616,https://www.airbnb.com/rooms/44616,20230329041210,2023-03-30,city scrape,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,https://a0.muscache.com/pictures/251410/ec75fe...,196253,https://www.airbnb.com/users/show/196253,...,5.0,"[""Free street parking"", ""Security cameras on p...",0.0,t,2023-03-30,2011-11-09,2023-03-26,--,f,--
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,853923589855678923,https://www.airbnb.com/rooms/853923589855678923,20230329041210,2023-03-30,city scrape,Rincón Mexico lindo!,Este lugar tiene una ubicación estratégica: ll...,https://a0.muscache.com/pictures/miso/Hosting-...,488030249,https://www.airbnb.com/users/show/488030249,...,1.0,"[""Smoke alarm"", ""Wifi"", ""Iron"", ""Washer"", ""Sel...",0.0,t,2023-03-30,--,--,--,f,--
24220,853966732274073000,https://www.airbnb.com/rooms/853966732274073000,20230329041210,2023-03-29,city scrape,Departamento en zona diamante.,"Ubicado en zona diamante, junto al aeropuerto,...",https://a0.muscache.com/pictures/miso/Hosting-...,506816029,https://www.airbnb.com/users/show/506816029,...,2.0,"[""Lake access"", ""Ski-in/Ski-out"", ""Wifi"", ""Out...",0.0,t,2023-03-29,--,--,--,t,--
24221,854225071295768399,https://www.airbnb.com/rooms/854225071295768399,20230329041210,2023-03-29,city scrape,Habitación privada en magnífica casa,Relájate en este espacio muy tranquilo y elega...,https://a0.muscache.com/pictures/db71951a-8696...,154670560,https://www.airbnb.com/users/show/154670560,...,2.0,"[""Luggage dropoff allowed"", ""Shared patio or b...",0.0,t,2023-03-29,--,--,--,f,--
24222,854247693069190865,https://www.airbnb.com/rooms/854247693069190865,20230329041210,2023-03-30,city scrape,Espacioso y luminoso loft - Roma,What else does it come with?<br />- WIFI 100MB...,https://a0.muscache.com/pictures/miso/Hosting-...,7799414,https://www.airbnb.com/users/show/7799414,...,1.0,"[""Smoke alarm"", ""Free street parking"", ""Condit...",0.0,t,2023-03-30,--,--,--,t,--
24223,854260329845513725,https://www.airbnb.com/rooms/854260329845513725,20230329041210,2023-03-30,city scrape,Maravilloso departamento en Ciudad de México,Ven a descubrir este increíble departamento en...,https://a0.muscache.com/pictures/miso/Hosting-...,506864314,https://www.airbnb.com/users/show/506864314,...,3.0,"[""Long term stays allowed"", ""Cleaning products...",0.0,t,2023-03-30,--,--,--,t,Una zona muy bonita ya que varias de las atrac...

In [ ]:
#Método aplicando desviación estandar. Encuentro los valores extremos
y=mex_cuanti
Limite_Superior= y.mean() + 3*y.std()
Limite_Inferior= y.mean() - 3*y.std()
print("Limite superior permitido", Limite_Superior)
print("Limite inferior permitido", Limite_Inferior)

<ipython-input-43-eb0d5962c2c9>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Superior= y.mean() + 3*y.std()
<ipython-input-43-eb0d5962c2c9>:3: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Superior= y.mean() + 3*y.std()

Limite superior permitido host_listings_count                              252.830274
latitude                                          19.532575
longitude                                        -99.065630
accommodates                                       9.933140
bathrooms                                          0.000000
beds                                               6.950262
minimum_nights                                    84.914542
maximum_nights                                  2018.371832
minimum_minimum_nights                            74.570417
maximum_minimum_nights                            75.639911
minimum_maximum_nights                          2164.959266
maximum_maximum_nights                          2164.414042
minimum_nights_avg_ntm                            74.890038
maximum_nights_avg_ntm                          2159.245933
calendar_updated                                   0.000000
availability_30                                   49.824183
availability_60                                  101.327447
availability_90                                  152.257190
availability_365                                 617.302497
number_of_reviews                                226.110805
number_of_reviews_ltm                             74.249659
number_of_reviews_l30d                             6.890766
review_scores_rating                               9.251259
review_scores_accuracy                             9.333882
review_scores_cleanliness                          9.277534
review_scores_checkin                              9.403681
review_scores_communication                        9.392440
review_scores_location                             9.398230
review_scores_value                                9.212496
calculated_host_listings_count                   109.165728
calculated_host_listings_count_entire_homes      102.205923
calculated_host_listings_count_private_rooms      19.370955
calculated_host_listings_count_shared_rooms        7.991190
reviews_per_month                                  7.018884
dtype: float64
Limite inferior permitido host_listings_count                            -209.697183
latitude                                         19.273219
longitude                                       -99.270319
accommodates                                     -3.366099
bathrooms                                         0.000000
beds                                             -3.071547
minimum_nights                                  -75.637296
maximum_nights                                 -770.279032
minimum_minimum_nights                          -65.761633
maximum_minimum_nights                          -66.185404
minimum_maximum_nights                         -465.671205
maximum_maximum_nights                         -439.680307
minimum_nights_avg_ntm                          -65.807772
maximum_nights_avg_ntm                         -443.457715
calendar_updated                                  0.000000
availability_30                                 -18.564524
availability_60                                 -26.838593
availability_90                                 -30.190810
availability_365                               -126.114915
number_of_reviews                              -152.940395
number_of_reviews_ltm                           -47.405702
number_of_reviews_l30d                           -4.643242
review_scores_rating                             -1.216432
review_scores_accuracy                           -1.219203
review_scores_cleanliness                        -1.215572
review_scores_checkin                            -1.204888
review_scores_communication                      -1.213349
review_scores_location                           -1.190506
review_scores_value                              -1.215293
calculated_host_listings_count                  -83.335147
calculated_host_listings_count_entire_homes     -81.767267
calculated_host_listings_count_private_rooms    -14.542272
calculated_host_listings_count_shared_rooms      -7.536434
reviews_per_month                                -4.119460
dtype: float64

<ipython-input-43-eb0d5962c2c9>:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Inferior= y.mean() - 3*y.std()
<ipython-input-43-eb0d5962c2c9>:4: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Inferior= y.mean() - 3*y.std()

In [ ]:
#Encontramos Outliers del Dataframe
outliers= mex_cuanti[(y>Limite_Superior)|(y<Limite_Inferior)]
outliers

<ipython-input-44-0ceb496bcc68>:2: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  outliers= mex_cuanti[(y>Limite_Superior)|(y<Limite_Inferior)]

,neighborhood_overview,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,beds,price,minimum_nights,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,neiborhood_overview
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,-99.27178,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,14.0,NaN,8.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Obtenemos datos y los outliers se convierten en nulos en el DataFrame
mex2 = mex_cuanti[(y<=Limite_Superior)&(y>=Limite_Inferior)]
mex2

<ipython-input-45-b85f4f6c64dd>:2: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  mex2 = mex_cuanti[(y<=Limite_Superior)&(y>=Limite_Inferior)]

,neighborhood_overview,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,beds,price,minimum_nights,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,neiborhood_overview
0,NaN,NaN,3.0,19.353530,-99.162990,3.0,0.0,1.0,NaN,1.0,...,5.00,4.95,5.00,4.86,3.0,3.0,0.0,0.0,0.19,NaN
1,NaN,NaN,3.0,19.353580,-99.169480,2.0,0.0,1.0,NaN,3.0,...,4.93,5.00,4.95,4.84,2.0,2.0,0.0,0.0,0.54,NaN
2,NaN,NaN,4.0,19.441800,-99.184020,6.0,0.0,3.0,NaN,24.0,...,4.92,4.92,4.58,4.71,3.0,3.0,0.0,0.0,0.31,NaN
3,NaN,NaN,1.0,19.382830,NaN,2.0,0.0,1.0,NaN,1.0,...,0.00,0.00,0.00,0.00,1.0,1.0,0.0,0.0,0.00,NaN
4,NaN,NaN,16.0,19.411620,-99.177940,NaN,0.0,NaN,NaN,1.0,...,4.87,4.78,4.98,4.48,12.0,3.0,2.0,0.0,0.46,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,NaN,NaN,3.0,19.396663,-99.148145,2.0,0.0,1.0,NaN,3.0,...,0.00,0.00,0.00,0.00,2.0,2.0,0.0,0.0,0.00,NaN
24220,NaN,NaN,1.0,19.392023,-99.118722,7.0,0.0,3.0,NaN,1.0,...,0.00,0.00,0.00,0.00,1.0,1.0,0.0,0.0,0.00,NaN
24221,NaN,NaN,1.0,19.371088,-99.190186,2.0,0.0,1.0,NaN,5.0,...,0.00,0.00,0.00,0.00,1.0,0.0,1.0,0.0,0.00,NaN
24222,NaN,NaN,13.0,19.403792,-99.164978,2.0,0.0,1.0,NaN,1.0,...,0.00,0.00,0.00,0.00,13.0,13.0,0.0,0.0,0.00,NaN
24223,NaN,NaN,2.0,19.426283,-99.175603,6.0,0.0,3.0,NaN,1.0,...,0.00,0.00,0.00,0.00,2.0,2.0,0.0,0.0,0.00,NaN

In [ ]:
#Corroboramos valores nulos del dataframe4
valores_nulos=mex_cuanti.isnull().sum()
valores_nulos

neighborhood_overview                           0
host_acceptance_rate                            0
host_listings_count                             0
latitude                                        0
longitude                                       0
accommodates                                    0
bathrooms                                       0
beds                                            0
price                                           0
minimum_nights                                  0
maximum_nights                                  0
minimum_minimum_nights                          0
maximum_minimum_nights                          0
minimum_maximum_nights                          0
maximum_maximum_nights                          0
minimum_nights_avg_ntm                          0
maximum_nights_avg_ntm                          0
calendar_updated                                0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
number_of_reviews                               0
number_of_reviews_ltm                           0
number_of_reviews_l30d                          0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
review_scores_value                             0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
neiborhood_overview                             0
dtype: int64

In [ ]:
#Reemplazamos valores atípicos (nulos) del dataframe con "mean"
#Realizamos una copia del dataframe
data_clean=mex_cuanti.copy()
data_clean=data_clean.fillna(round(mex_cuanti.mean(),1))
data_clean

<ipython-input-47-9cb7c9df8cb1>:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data_clean=data_clean.fillna(round(mex_cuanti.mean(),1))

,neighborhood_overview,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,beds,price,minimum_nights,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,neiborhood_overview
0,0,0%,3,19.353530,-99.162990,3,0.0,1.0,"$1,434.00",1,...,5.00,4.95,5.00,4.86,3,3,0,0,0.19,--
1,"Located in Coyoacan, in a quiet neighborhood w...",0%,3,19.353580,-99.169480,2,0.0,1.0,$830.00,3,...,4.93,5.00,4.95,4.84,2,2,0,0,0.54,"Located in Coyoacan, in a quiet neighborhood w..."
2,"This area is called Nuevo Polanco, it has bein...",90%,4,19.441800,-99.184020,6,0.0,3.0,"$1,469.00",24,...,4.92,4.92,4.58,4.71,3,3,0,0,0.31,"This area is called Nuevo Polanco, it has bein..."
3,"Centro comercial Santa Fe, parque interlomas y...",0%,1,19.382830,-99.271780,2,0.0,1.0,"$3,658.00",1,...,0.00,0.00,0.00,0.00,1,1,0,0,0.00,"Centro comercial Santa Fe, parque interlomas y..."
4,0,86%,16,19.411620,-99.177940,14,0.0,8.0,"$18,000.00",1,...,4.87,4.78,4.98,4.48,12,3,2,0,0.46,--
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,0,100%,3,19.396663,-99.148145,2,0.0,1.0,$760.00,3,...,0.00,0.00,0.00,0.00,2,2,0,0,0.00,--
24220,0,0%,1,19.392023,-99.118722,7,0.0,3.0,"$1,520.00",1,...,0.00,0.00,0.00,0.00,1,1,0,0,0.00,--
24221,0,96%,1,19.371088,-99.190186,2,0.0,1.0,$533.00,5,...,0.00,0.00,0.00,0.00,1,0,1,0,0.00,--
24222,0,100%,13,19.403792,-99.164978,2,0.0,1.0,"$1,200.00",1,...,0.00,0.00,0.00,0.00,13,13,0,0,0.00,--
24223,Una zona muy bonita ya que varias de las atrac...,100%,2,19.426283,-99.175603,6,0.0,3.0,"$1,720.00",1,...,0.00,0.00,0.00,0.00,2,2,0,0,0.00,Una zona muy bonita ya que varias de las atrac...

In [ ]:
#Corroboramos valores nulos del dataframe LIMPIO
valores_nulos=data_clean.isnull().sum()
valores_nulos

In [ ]:
# Unimos los datas con el dataframe
mex_clean = pd.concat([mex_cuali,mex_cuanti], axis=1)
mex_clean

In [ ]:
#Convertir DataFrame a CSV
mex_clean.to_csv("DF_México_clean.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("DF_México_clean.csv")