<a href="https://colab.research.google.com/github/andilugo/Evaluacion/blob/main/Evaluacion_Parte1_EUA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Evaluación Parte1 EUA
Andrea Cosset Hernández Lugo A01707744

In [1]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
#Leemos el codigo 
eua= pd.read_csv("California_EUA.csv", encoding = 'unicode_escape')
eua

,ï»¿id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,9.580000e+02,https://www.airbnb.com/rooms/958,2.020000e+13,06/03/2023,city scrape,"Bright, Modern Garden Unit - 1BR/1BTH",Our bright garden unit overlooks a lovely back...,Quiet cul de sac in friendly neighborhood<br /...,https://a0.muscache.com/pictures/b7c2a199-4c17...,1169,...,4.88,4.98,4.76,City Registration Pending,f,1,1,0,0,2.31
1,5.858000e+03,https://www.airbnb.com/rooms/5858,2.020000e+13,06/03/2023,city scrape,Creative Sanctuary,We live in a large Victorian house on a quiet ...,I love how our neighborhood feels quiet but is...,https://a0.muscache.com/pictures/17714/3a7aea1...,8904,...,4.85,4.77,4.68,NaN,f,1,1,0,0,0.66
2,8.142000e+03,https://www.airbnb.com/rooms/8142,2.020000e+13,06/03/2023,city scrape,Friendly Room Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,"N Juda Muni, Bus and UCSF Shuttle.<br /><br />...",https://a0.muscache.com/pictures/12d8bff0-1698...,21994,...,4.78,4.67,4.67,NaN,f,13,0,13,0,0.09
3,8.339000e+03,https://www.airbnb.com/rooms/8339,2.020000e+13,06/03/2023,city scrape,Historic Alamo Square Victorian,Pls email before booking. <br />Interior featu...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,24215,...,5.00,4.94,4.75,STR-0000264,f,2,2,0,0,0.17
4,8.739000e+03,https://www.airbnb.com/rooms/8739,2.020000e+13,06/03/2023,city scrape,"Mission Sunshine, with Private Bath","Welcome to ""The Mission,"" the sunniest neighbo...",Located between Valencia Street and Dolores Pa...,https://a0.muscache.com/pictures/80811/7a57d0e...,7149,...,4.96,4.93,4.74,STR-0000028,f,2,0,2,0,4.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,8.180000e+17,https://www.airbnb.com/rooms/818195233784141985,2.020000e+13,06/03/2023,city scrape,Powell Place Studio on Nob Hill,Situated in the prestigious Nob Hill section o...,Powell Place is surrounded by everything that ...,https://a0.muscache.com/pictures/miso/Hosting-...,495900269,...,NaN,NaN,NaN,147904,t,5,5,0,0,NaN
6932,8.180000e+17,https://www.airbnb.com/rooms/818231243893035313,2.020000e+13,06/03/2023,city scrape,Ã¢â¬Â¢ Cozy & Comfortable Castro Artist's Stu...,You'll be in the perfect location to explore a...,"Lively and safe neighborhood, with a local lib...",https://a0.muscache.com/pictures/miso/Hosting-...,499392537,...,5.00,5.00,5.00,2023-001477STR,f,1,1,0,0,1.00
6933,8.180000e+17,https://www.airbnb.com/rooms/818396267693629070,2.020000e+13,06/03/2023,city scrape,Heart of SF ! Close by to Everything,- In-unit washer/dryer<br />-Walk-in Closet <b...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,499294716,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
6934,8.180000e+17,https://www.airbnb.com/rooms/818474518435984613,2.020000e+13,06/03/2023,city scrape,Private room #2 in SF,Enjoy a memorable visit when you stay at our A...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,485596413,...,NaN,NaN,NaN,2022-012562STR,f,3,0,3,0,NaN
6935,8.190000e+17,https://www.airbnb.com/rooms/818887060432463897,2.020000e+13,06/03/2023,city scrape,Sunny Garden Apartment,This sunny garden apartment is located in Laur...,"Laurel Heights is a quiet, refined neighborhoo...",https://a0.muscache.com/pictures/miso/Hosting-...,4836128,...,NaN,NaN,NaN,NaN,t,2,1,1,0,NaN

In [7]:
eua.head()

,ï»¿id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,958.0,https://www.airbnb.com/rooms/958,2.020000e+13,06/03/2023,city scrape,"Bright, Modern Garden Unit - 1BR/1BTH",Our bright garden unit overlooks a lovely back...,Quiet cul de sac in friendly neighborhood<br /...,https://a0.muscache.com/pictures/b7c2a199-4c17...,1169,...,4.88,4.98,4.76,City Registration Pending,f,1,1,0,0,2.31
1,5858.0,https://www.airbnb.com/rooms/5858,2.020000e+13,06/03/2023,city scrape,Creative Sanctuary,We live in a large Victorian house on a quiet ...,I love how our neighborhood feels quiet but is...,https://a0.muscache.com/pictures/17714/3a7aea1...,8904,...,4.85,4.77,4.68,NaN,f,1,1,0,0,0.66
2,8142.0,https://www.airbnb.com/rooms/8142,2.020000e+13,06/03/2023,city scrape,Friendly Room Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,"N Juda Muni, Bus and UCSF Shuttle.<br /><br />...",https://a0.muscache.com/pictures/12d8bff0-1698...,21994,...,4.78,4.67,4.67,NaN,f,13,0,13,0,0.09
3,8339.0,https://www.airbnb.com/rooms/8339,2.020000e+13,06/03/2023,city scrape,Historic Alamo Square Victorian,Pls email before booking. <br />Interior featu...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,24215,...,5.00,4.94,4.75,STR-0000264,f,2,2,0,0,0.17
4,8739.0,https://www.airbnb.com/rooms/8739,2.020000e+13,06/03/2023,city scrape,"Mission Sunshine, with Private Bath","Welcome to ""The Mission,"" the sunniest neighbo...",Located between Valencia Street and Dolores Pa...,https://a0.muscache.com/pictures/80811/7a57d0e...,7149,...,4.96,4.93,4.74,STR-0000028,f,2,0,2,0,4.65

In [8]:
eua.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6936 entries, 0 to 6935
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   ï»¿id                                         6936 non-null   float64
 1   listing_url                                   6936 non-null   object
 2   scrape_id                                     6936 non-null   float64
 3   last_scraped                                  6936 non-null   object
 4   source                                        6936 non-null   object
 5   name                                          6936 non-null   object
 6   description                                   6889 non-null   object
 7   neighborhood_overview                         4850 non-null   object
 8   picture_url                                   6936 non-null   object
 9   host_id                                       6936 non-null   int64
 10  host_url                                      6936 non-null   object
 11  host_name                                     6936 non-null   object
 12  host_since                                    6936 non-null   object
 13  host_location                                 5715 non-null   object
 14  host_about                                    4684 non-null   object
 15  host_response_time                            5917 non-null   object
 16  host_response_rate                            5917 non-null   object
 17  host_acceptance_rate                          6135 non-null   object
 18  host_is_superhost                             6927 non-null   object
 19  host_thumbnail_url                            6936 non-null   object
 20  host_picture_url                              6936 non-null   object
 21  host_neighbourhood                            6635 non-null   object
 22  host_listings_count                           6936 non-null   int64
 23  host_total_listings_count                     6936 non-null   int64
 24  host_verifications                            6936 non-null   object
 25  host_has_profile_pic                          6936 non-null   object
 26  host_identity_verified                        6936 non-null   object
 27  neighbourhood                                 4850 non-null   object
 28  neighbourhood_cleansed                        6936 non-null   object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      6936 non-null   float64
 31  longitude                                     6936 non-null   float64
 32  property_type                                 6936 non-null   object
 33  room_type                                     6936 non-null   object
 34  accommodates                                  6936 non-null   int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                6922 non-null   object
 37  bedrooms                                      5991 non-null   float64
 38  beds                                          6816 non-null   float64
 39  amenities                                     6936 non-null   object
 40  price                                         6936 non-null   object
 41  minimum_nights                                6936 non-null   int64
 42  maximum_nights                                6936 non-null   int64
 43  minimum_minimum_nights                        6934 non-null   float64
 44  maximum_minimum_nights                        6934 non-null   float64
 45  minimum_maximum_nights                        6934 non-null   float64
 46  maximum_maximum_nights                        6934 non-null   float64
 47  minimum_nights_avg_ntm                        6934 non-null   float64
 48  maximum_nights_avg_ntm                        6934 non-null   float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              6936 non-null   object
 51  availability_30                               6936 non-null   int64
 52  availability_60                               6936 non-null   int64
 53  availability_90                               6936 non-null   int64
 54  availability_365                              6936 non-null   int64
 55  calendar_last_scraped                         6936 non-null   object
 56  number_of_reviews                             6936 non-null   int64
 57  number_of_reviews_ltm                         6936 non-null   int64
 58  number_of_reviews_l30d                        6936 non-null   int64
 59  first_review                                  5611 non-null   object
 60  last_review                                   5611 non-null   object
 61  review_scores_rating                          5611 non-null   float64
 62  review_scores_accuracy                        5590 non-null   float64
 63  review_scores_cleanliness                     5590 non-null   float64
 64  review_scores_checkin                         5589 non-null   float64
 65  review_scores_communication                   5590 non-null   float64
 66  review_scores_location                        5589 non-null   float64
 67  review_scores_value                           5589 non-null   float64
 68  license                                       4178 non-null   object
 69  instant_bookable                              6936 non-null   object
 70  calculated_host_listings_count                6936 non-null   int64
 71  calculated_host_listings_count_entire_homes   6936 non-null   int64
 72  calculated_host_listings_count_private_rooms  6936 non-null   int64
 73  calculated_host_listings_count_shared_rooms   6936 non-null   int64
 74  reviews_per_month                             5611 non-null   float64
dtypes: float64(23), int64(17), object(35)
memory usage: 4.0+ MB

In [9]:
#Identificar los valores nulos por columna 
valores_nulos= eua.isnull().sum()
valores_nulos

ï»¿id                                              0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1325
Length: 75, dtype: int64

In [10]:
valores_nulos.to_csv("valores_nulos.csv")

In [11]:
#Identificar valores nulos por dataframe
valores_nulos= eua.isnull().sum().sum()
valores_nulos

48877

In [ ]:
#valores cualitativos
eua["description"] =eua["description"].fillna("--") 
eua["neighborhood_overview"] =eua["neighborhood_overview"].fillna("--") 
eua["host_location"] =eua["host_location"].fillna("--") 
eua["host_about"] =eua["host_about"].fillna("--") 
eua["host_response_time"] =eua["host_response_time"].fillna("--") 
eua["host_response_rate"] =eua["host_response_rate"].fillna("0%") 
eua["host_acceptance_rate"] =eua["host_acceptance_rate"].fillna("0%") 
eua["host_is_superhost"] =eua["host_is_superhost"].fillna("--") 
eua["host_neighbourhood"] =eua["host_neighbourhood"].fillna("--") 
eua["neighbourhood"] =eua["neighbourhood"].fillna("--") 
eua["neighbourhood_group_cleansed"] =eua["neighbourhood_group_cleansed"].fillna("--") 
eua["bathrooms_text"] =eua["bathrooms_text"].fillna("--") 
eua["last_review"] =eua["last_review"].fillna("--") 
eua["first_review"] =eua["first_review"].fillna("--") 
eua["calendar_updated"] =eua["calendar_updated"].fillna("--")

In [12]:
#Verificamos los valores nulos no numericos 
valores_nulos= eua.isnull().sum()
valores_nulos

ï»¿id                                              0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1325
Length: 75, dtype: int64

In [13]:
valores_nulos= eua.isnull().sum().sum()
valores_nulos

48877

In [14]:
#Los valores numericos los llenamos con un 0 para no alterar los resultados 
eua= eua.fillna(0)

In [15]:
valores_nulos= eua.isnull().sum()
valores_nulos

ï»¿id                                           0
listing_url                                     0
scrape_id                                       0
last_scraped                                    0
source                                          0
                                               ..
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
Length: 75, dtype: int64

In [16]:
valores_nulos= eua.isnull().sum().sum()
valores_nulos

0

##Metodo de desviacion estandar

In [17]:
#Instalamos librería para análisis de variables categóricas
%pip install funpymodeling

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting funpymodeling
  Downloading funpymodeling-0.1.7-py3-none-any.whl (6.4 kB)
Requirement already satisfied: pandas<2.0.0,>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from funpymodeling) (1.5.3)
Collecting sklearn<0.1,>=0.0
  Downloading sklearn-0.0.post4.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib<4.0.0,>=3.2.2 in /usr/local/lib/python3.10/dist-packages (from funpymodeling) (3.7.1)
Requirement already satisfied: numpy<2.0.0,>=1.18.5 in /usr/local/lib/python3.10/dist-packages (from funpymodeling) (1.22.4)
Collecting seaborn<0.11.0,>=0.10.1
  Downloading seaborn-0.10.1-py3-none-any.whl (215 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.5/215.5 kB 6.5 MB/s eta 0:00:00
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (8.4.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (2.8.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (23.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.2.2->funpymodeling) (4.39.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.0.5->funpymodeling) (2022.7.1)
Requirement already satisfied: scipy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from seaborn<0.11.0,>=0.10.1->funpymodeling) (1.10.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib<4.0.0,>=3.2.2->funpymodeling) (1.16.0)
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post4-py3-none-any.whl size=2973 sha256=fe8ed5d8f3e110906b84e0e06781f8646d0770f590fc1275c997c708222c83e5
  Stored in directory: /root/.cache/pip/wheels/46/b8/69/4f7789b7d2fc0718a44cbc4ae5d40970a40c22c472ae50f0a1
Successfully built sklearn
Installing collected packages: sklearn, seaborn, funpymodeling
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.12.2
    Uninstalling seaborn-0.12.2:
      Successfully uninstalled seaborn-0.12.2
Successfully installed funpymodeling-0.1.7 seaborn-0.10.1 sklearn-0.0.post4

In [18]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
from seaborn import load_dataset
import numpy as np
import matplotlib.pyplot as plt
from funpymodeling.exploratory import freq_tbl

In [19]:
num_eua=eua.drop(['ï»¿id','listing_url','scrape_id','last_scraped','source','name','description','neighborhood_overview', 'picture_url','host_id','host_url','host_name','host_since','host_location','host_about','host_response_time','host_response_rate','host_acceptance_rate','host_is_superhost', 'host_thumbnail_url','host_picture_url','host_neighbourhood','host_total_listings_count','host_verifications', 'host_has_profile_pic', 'host_identity_verified','neighbourhood','neighbourhood_cleansed','neighbourhood_group_cleansed','property_type','room_type','bathrooms_text','amenities','has_availability','calendar_last_scraped','first_review','last_review','license','instant_bookable',], axis=1)
num_eua

,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,1,37.770280,-122.433170,3,0.0,1.0,2.0,$202.00,2,30,...,4.92,4.95,4.88,4.98,4.76,1,1,0,0,2.31
1,2,37.744740,-122.420890,4,0.0,2.0,2.0,$235.00,30,60,...,4.87,4.89,4.85,4.77,4.68,1,1,0,0,0.66
2,13,37.765550,-122.452130,1,0.0,1.0,1.0,$56.00,32,90,...,4.44,4.78,4.78,4.67,4.67,13,0,13,0,0.09
3,2,37.775640,-122.436420,4,0.0,2.0,2.0,$575.00,9,91,...,5.00,4.94,5.00,4.94,4.75,2,2,0,0,0.17
4,2,37.760300,-122.421970,3,0.0,1.0,1.0,$110.00,1,26,...,4.94,4.95,4.96,4.93,4.74,2,0,2,0,4.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,9,37.791994,-122.410000,2,0.0,1.0,1.0,$164.00,1,28,...,0.00,0.00,0.00,0.00,0.00,5,5,0,0,0.00
6932,1,37.763060,-122.432023,2,0.0,1.0,1.0,$228.00,1,7,...,5.00,5.00,5.00,5.00,5.00,1,1,0,0,1.00
6933,1,37.777633,-122.416478,1,0.0,1.0,1.0,$104.00,31,60,...,0.00,0.00,0.00,0.00,0.00,1,0,1,0,0.00
6934,3,37.738325,-122.396603,2,0.0,1.0,1.0,$65.00,1,7,...,0.00,0.00,0.00,0.00,0.00,3,0,3,0,0.00
6935,2,37.786442,-122.457006,2,0.0,1.0,1.0,$375.00,30,365,...,0.00,0.00,0.00,0.00,0.00,2,1,1,0,0.00

In [20]:
cuali_eua=eua.drop(['host_response_rate'	,'host_acceptance_rate', 'host_listings_count', 'host_total_listings_count','latitude','longitude','accommodates','beds','price','minimum_nights','maximum_nights','minimum_minimum_nights','maximum_minimum_nights','minimum_maximum_nights','maximum_maximum_nights','minimum_nights_avg_ntm','maximum_nights_avg_ntm','availability_30','availability_60','availability_90','availability_365','number_of_reviews','number_of_reviews_ltm','number_of_reviews_l30d','review_scores_rating','review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value','calculated_host_listings_count','calculated_host_listings_count_entire_homes','calculated_host_listings_count_private_rooms','calculated_host_listings_count_shared_rooms','reviews_per_month'], axis=1)
cuali_eua

,ï»¿id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,bathrooms_text,bedrooms,amenities,calendar_updated,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,9.580000e+02,https://www.airbnb.com/rooms/958,2.020000e+13,06/03/2023,city scrape,"Bright, Modern Garden Unit - 1BR/1BTH",Our bright garden unit overlooks a lovely back...,Quiet cul de sac in friendly neighborhood<br /...,https://a0.muscache.com/pictures/b7c2a199-4c17...,1169,...,1 bath,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",0.0,t,06/03/2023,23/07/2009,19/02/2023,City Registration Pending,f
1,5.858000e+03,https://www.airbnb.com/rooms/5858,2.020000e+13,06/03/2023,city scrape,Creative Sanctuary,We live in a large Victorian house on a quiet ...,I love how our neighborhood feels quiet but is...,https://a0.muscache.com/pictures/17714/3a7aea1...,8904,...,1 bath,2.0,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",0.0,t,06/03/2023,03/05/2009,06/08/2017,0,f
2,8.142000e+03,https://www.airbnb.com/rooms/8142,2.020000e+13,06/03/2023,city scrape,Friendly Room Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,"N Juda Muni, Bus and UCSF Shuttle.<br /><br />...",https://a0.muscache.com/pictures/12d8bff0-1698...,21994,...,4 shared baths,1.0,"[""Security cameras on property"", ""Host greets ...",0.0,t,06/03/2023,08/09/2014,27/10/2022,0,f
3,8.339000e+03,https://www.airbnb.com/rooms/8339,2.020000e+13,06/03/2023,city scrape,Historic Alamo Square Victorian,Pls email before booking. <br />Interior featu...,0,https://a0.muscache.com/pictures/miso/Hosting-...,24215,...,1.5 baths,2.0,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",0.0,t,06/03/2023,25/09/2009,28/06/2019,STR-0000264,f
4,8.739000e+03,https://www.airbnb.com/rooms/8739,2.020000e+13,06/03/2023,city scrape,"Mission Sunshine, with Private Bath","Welcome to ""The Mission,"" the sunniest neighbo...",Located between Valencia Street and Dolores Pa...,https://a0.muscache.com/pictures/80811/7a57d0e...,7149,...,1 private bath,1.0,"[""Paid parking garage off premises"", ""Luggage ...",0.0,t,06/03/2023,01/08/2009,25/02/2023,STR-0000028,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,8.180000e+17,https://www.airbnb.com/rooms/818195233784141985,2.020000e+13,06/03/2023,city scrape,Powell Place Studio on Nob Hill,Situated in the prestigious Nob Hill section o...,Powell Place is surrounded by everything that ...,https://a0.muscache.com/pictures/miso/Hosting-...,495900269,...,1 bath,1.0,"[""Security cameras on property"", ""Self check-i...",0.0,t,06/03/2023,0,0,147904,t
6932,8.180000e+17,https://www.airbnb.com/rooms/818231243893035313,2.020000e+13,06/03/2023,city scrape,Ã¢â¬Â¢ Cozy & Comfortable Castro Artist's Stu...,You'll be in the perfect location to explore a...,"Lively and safe neighborhood, with a local lib...",https://a0.muscache.com/pictures/miso/Hosting-...,499392537,...,1 bath,1.0,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",0.0,t,06/03/2023,03/03/2023,03/03/2023,2023-001477STR,f
6933,8.180000e+17,https://www.airbnb.com/rooms/818396267693629070,2.020000e+13,06/03/2023,city scrape,Heart of SF ! Close by to Everything,- In-unit washer/dryer<br />-Walk-in Closet <b...,0,https://a0.muscache.com/pictures/miso/Hosting-...,499294716,...,1 shared bath,1.0,"[""TV"", ""Free dryer – In unit"", ""Mountain view""...",0.0,t,06/03/2023,0,0,0,f
6934,8.180000e+17,https://www.airbnb.com/rooms/818474518435984613,2.020000e+13,06/03/2023,city scrape,Private room #2 in SF,Enjoy a memorable visit when you stay at our A...,0,https://a0.muscache.com/pictures/miso/Hosting-...,485596413,...,1 shared bath,1.0,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",0.0,t,06/03/2023,0,0,2022-012562STR,f
6935,8.190000e+17,https://www.airbnb.com/rooms/818887060432463897,2.020000e+13,06/03/2023,city scrape,Sunny Garden Apartment,This sunny garden apartment is located in Laur...,"Laurel Heights is a quiet, refined neighborhoo...",https://a0.muscache.com/pictures/miso/Hosting-...,4836128,...,1 bath,1.0,"[""Carbon monoxide alarm"", ""Security cameras on...",0.0,t,06/03/2023,0,0,0,t

In [21]:
#Método aplicando desviación estandar. Encuentro los valores extremos
y=num_eua
Limite_Superior= y.mean() + 3*y.std()
Limite_Inferior= y.mean() - 3*y.std()
print("Limite superior permitido", Limite_Superior)
print("Limite inferior permitido", Limite_Inferior)

Limite superior permitido host_listings_count                             2.300397e+03
latitude                                        3.783716e+01
longitude                                      -1.223476e+02
accommodates                                    9.034994e+00
bathrooms                                       0.000000e+00
bedrooms                                        4.326313e+00
beds                                            5.409527e+00
minimum_nights                                  1.755102e+02
maximum_nights                                  3.662171e+04
minimum_minimum_nights                          1.955322e+02
maximum_minimum_nights                          2.404520e+02
minimum_maximum_nights                          3.039426e+08
maximum_maximum_nights                          4.321010e+08
minimum_nights_avg_ntm                          2.361379e+02
maximum_nights_avg_ntm                          4.031692e+08
calendar_updated                                0.000000e+00
availability_30                                 4.639164e+01
availability_60                                 9.577126e+01
availability_90                                 1.465721e+02
availability_365                                5.574500e+02
number_of_reviews                               3.315465e+02
number_of_reviews_ltm                           7.831711e+01
number_of_reviews_l30d                          5.179824e+00
review_scores_rating                            9.600710e+00
review_scores_accuracy                          9.685768e+00
review_scores_cleanliness                       9.606425e+00
review_scores_checkin                           9.783417e+00
review_scores_communication                     9.754512e+00
review_scores_location                          9.633884e+00
review_scores_value                             9.417494e+00
calculated_host_listings_count                  1.046359e+02
calculated_host_listings_count_entire_homes     9.811532e+01
calculated_host_listings_count_private_rooms    3.221346e+01
calculated_host_listings_count_shared_rooms     6.452876e+00
reviews_per_month                               6.482761e+00
dtype: float64
Limite inferior permitido host_listings_count                            -1.997057e+03
latitude                                        3.769951e+01
longitude                                      -1.225130e+02
accommodates                                   -2.601603e+00
bathrooms                                       0.000000e+00
bedrooms                                       -1.623314e+00
beds                                           -1.846379e+00
minimum_nights                                 -1.304886e+02
maximum_nights                                 -3.545389e+04
minimum_minimum_nights                         -1.470213e+02
maximum_minimum_nights                         -1.811339e+02
minimum_maximum_nights                         -2.946526e+08
maximum_maximum_nights                         -4.135226e+08
minimum_nights_avg_ntm                         -1.779146e+02
maximum_nights_avg_ntm                         -3.864050e+08
calendar_updated                                0.000000e+00
availability_30                                -2.357763e+01
availability_60                                -4.180759e+01
availability_90                                -5.752217e+01
availability_365                               -2.177816e+02
number_of_reviews                              -2.356584e+02
number_of_reviews_ltm                          -5.745407e+01
number_of_reviews_l30d                         -3.962119e+00
review_scores_rating                           -1.915018e+00
review_scores_accuracy                         -1.927366e+00
review_scores_cleanliness                      -1.921655e+00
review_scores_checkin                          -1.920364e+00
review_scores_communication                    -1.930147e+00
review_scores_location                         -1.919763e+00
review_scores_value                            -1.902318e+00
calculated_host_listings_count                 -7.763070e+01
calculated_host_listings_count_entire_homes    -7.948672e+01
calculated_host_listings_count_private_rooms   -2.452863e+01
calculated_host_listings_count_shared_rooms    -6.062450e+00
reviews_per_month                              -4.349344e+00
dtype: float64

<ipython-input-21-7990433469c1>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Superior= y.mean() + 3*y.std()
<ipython-input-21-7990433469c1>:3: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Superior= y.mean() + 3*y.std()
<ipython-input-21-7990433469c1>:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Inferior= y.mean() - 3*y.std()
<ipython-input-21-7990433469c1>:4: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Inferior= y.mean() - 3*y.std()

In [22]:
#Encontramos Outliers del Dataframe
outliers= num_eua[(y>Limite_Superior)|(y<Limite_Inferior)]
outliers

<ipython-input-22-ba3434240138>:2: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  outliers= num_eua[(y>Limite_Superior)|(y<Limite_Inferior)]

,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
#Obtenemos datos y los outliers se convierten en nulos en el DataFrame
data3= num_eua[(y<=Limite_Superior)&(y>=Limite_Inferior)]
data3

<ipython-input-23-bfee7a4257ab>:2: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  data3= num_eua[(y<=Limite_Superior)&(y>=Limite_Inferior)]

,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,1.0,37.770280,-122.433170,3.0,0.0,1.0,2.0,NaN,2.0,30.0,...,4.92,4.95,4.88,4.98,4.76,1.0,1.0,0.0,0.0,2.31
1,2.0,37.744740,-122.420890,4.0,0.0,2.0,2.0,NaN,30.0,60.0,...,4.87,4.89,4.85,4.77,4.68,1.0,1.0,0.0,0.0,0.66
2,13.0,37.765550,-122.452130,1.0,0.0,1.0,1.0,NaN,32.0,90.0,...,4.44,4.78,4.78,4.67,4.67,13.0,0.0,13.0,0.0,0.09
3,2.0,37.775640,-122.436420,4.0,0.0,2.0,2.0,NaN,9.0,91.0,...,5.00,4.94,5.00,4.94,4.75,2.0,2.0,0.0,0.0,0.17
4,2.0,37.760300,-122.421970,3.0,0.0,1.0,1.0,NaN,1.0,26.0,...,4.94,4.95,4.96,4.93,4.74,2.0,0.0,2.0,0.0,4.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,9.0,37.791994,-122.410000,2.0,0.0,1.0,1.0,NaN,1.0,28.0,...,0.00,0.00,0.00,0.00,0.00,5.0,5.0,0.0,0.0,0.00
6932,1.0,37.763060,-122.432023,2.0,0.0,1.0,1.0,NaN,1.0,7.0,...,5.00,5.00,5.00,5.00,5.00,1.0,1.0,0.0,0.0,1.00
6933,1.0,37.777633,-122.416478,1.0,0.0,1.0,1.0,NaN,31.0,60.0,...,0.00,0.00,0.00,0.00,0.00,1.0,0.0,1.0,0.0,0.00
6934,3.0,37.738325,-122.396603,2.0,0.0,1.0,1.0,NaN,1.0,7.0,...,0.00,0.00,0.00,0.00,0.00,3.0,0.0,3.0,0.0,0.00
6935,2.0,37.786442,-122.457006,2.0,0.0,1.0,1.0,NaN,30.0,365.0,...,0.00,0.00,0.00,0.00,0.00,2.0,1.0,1.0,0.0,0.00

In [24]:
#Corroboramos valores nulos del dataframe4
valores_nulos=num_eua.isnull().sum()
valores_nulos

host_listings_count                             0
latitude                                        0
longitude                                       0
accommodates                                    0
bathrooms                                       0
bedrooms                                        0
beds                                            0
price                                           0
minimum_nights                                  0
maximum_nights                                  0
minimum_minimum_nights                          0
maximum_minimum_nights                          0
minimum_maximum_nights                          0
maximum_maximum_nights                          0
minimum_nights_avg_ntm                          0
maximum_nights_avg_ntm                          0
calendar_updated                                0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
number_of_reviews                               0
number_of_reviews_ltm                           0
number_of_reviews_l30d                          0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
review_scores_value                             0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
dtype: int64

In [25]:
#Reemplazamos valores atípicos (nulos) del dataframe con "mean"
#Realizamos una copia del dataframe
data_clean=num_eua.copy()
data_clean=data_clean.fillna(round(num_eua.mean(),1))
data_clean

<ipython-input-25-33c6af70b66f>:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data_clean=data_clean.fillna(round(num_eua.mean(),1))

,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,1,37.770280,-122.433170,3,0.0,1.0,2.0,$202.00,2,30,...,4.92,4.95,4.88,4.98,4.76,1,1,0,0,2.31
1,2,37.744740,-122.420890,4,0.0,2.0,2.0,$235.00,30,60,...,4.87,4.89,4.85,4.77,4.68,1,1,0,0,0.66
2,13,37.765550,-122.452130,1,0.0,1.0,1.0,$56.00,32,90,...,4.44,4.78,4.78,4.67,4.67,13,0,13,0,0.09
3,2,37.775640,-122.436420,4,0.0,2.0,2.0,$575.00,9,91,...,5.00,4.94,5.00,4.94,4.75,2,2,0,0,0.17
4,2,37.760300,-122.421970,3,0.0,1.0,1.0,$110.00,1,26,...,4.94,4.95,4.96,4.93,4.74,2,0,2,0,4.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,9,37.791994,-122.410000,2,0.0,1.0,1.0,$164.00,1,28,...,0.00,0.00,0.00,0.00,0.00,5,5,0,0,0.00
6932,1,37.763060,-122.432023,2,0.0,1.0,1.0,$228.00,1,7,...,5.00,5.00,5.00,5.00,5.00,1,1,0,0,1.00
6933,1,37.777633,-122.416478,1,0.0,1.0,1.0,$104.00,31,60,...,0.00,0.00,0.00,0.00,0.00,1,0,1,0,0.00
6934,3,37.738325,-122.396603,2,0.0,1.0,1.0,$65.00,1,7,...,0.00,0.00,0.00,0.00,0.00,3,0,3,0,0.00
6935,2,37.786442,-122.457006,2,0.0,1.0,1.0,$375.00,30,365,...,0.00,0.00,0.00,0.00,0.00,2,1,1,0,0.00

In [26]:
#Corroboramos valores nulos del dataframe LIMPIO
valores_nulos=data_clean.isnull().sum()
valores_nulos

host_listings_count                             0
latitude                                        0
longitude                                       0
accommodates                                    0
bathrooms                                       0
bedrooms                                        0
beds                                            0
price                                           0
minimum_nights                                  0
maximum_nights                                  0
minimum_minimum_nights                          0
maximum_minimum_nights                          0
minimum_maximum_nights                          0
maximum_maximum_nights                          0
minimum_nights_avg_ntm                          0
maximum_nights_avg_ntm                          0
calendar_updated                                0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
number_of_reviews                               0
number_of_reviews_ltm                           0
number_of_reviews_l30d                          0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
review_scores_value                             0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
dtype: int64

In [29]:
# Unimos los datas con el dataframe
eua_clean= pd.concat([num_eua,cuali_eua], axis=1)
eua_clean

,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,...,bathrooms_text,bedrooms,amenities,calendar_updated,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,1,37.770280,-122.433170,3,0.0,1.0,2.0,$202.00,2,30,...,1 bath,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",0.0,t,06/03/2023,23/07/2009,19/02/2023,City Registration Pending,f
1,2,37.744740,-122.420890,4,0.0,2.0,2.0,$235.00,30,60,...,1 bath,2.0,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",0.0,t,06/03/2023,03/05/2009,06/08/2017,0,f
2,13,37.765550,-122.452130,1,0.0,1.0,1.0,$56.00,32,90,...,4 shared baths,1.0,"[""Security cameras on property"", ""Host greets ...",0.0,t,06/03/2023,08/09/2014,27/10/2022,0,f
3,2,37.775640,-122.436420,4,0.0,2.0,2.0,$575.00,9,91,...,1.5 baths,2.0,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",0.0,t,06/03/2023,25/09/2009,28/06/2019,STR-0000264,f
4,2,37.760300,-122.421970,3,0.0,1.0,1.0,$110.00,1,26,...,1 private bath,1.0,"[""Paid parking garage off premises"", ""Luggage ...",0.0,t,06/03/2023,01/08/2009,25/02/2023,STR-0000028,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,9,37.791994,-122.410000,2,0.0,1.0,1.0,$164.00,1,28,...,1 bath,1.0,"[""Security cameras on property"", ""Self check-i...",0.0,t,06/03/2023,0,0,147904,t
6932,1,37.763060,-122.432023,2,0.0,1.0,1.0,$228.00,1,7,...,1 bath,1.0,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",0.0,t,06/03/2023,03/03/2023,03/03/2023,2023-001477STR,f
6933,1,37.777633,-122.416478,1,0.0,1.0,1.0,$104.00,31,60,...,1 shared bath,1.0,"[""TV"", ""Free dryer – In unit"", ""Mountain view""...",0.0,t,06/03/2023,0,0,0,f
6934,3,37.738325,-122.396603,2,0.0,1.0,1.0,$65.00,1,7,...,1 shared bath,1.0,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",0.0,t,06/03/2023,0,0,2022-012562STR,f
6935,2,37.786442,-122.457006,2,0.0,1.0,1.0,$375.00,30,365,...,1 bath,1.0,"[""Carbon monoxide alarm"", ""Security cameras on...",0.0,t,06/03/2023,0,0,0,t

In [30]:
#Corroboramos valores nulos 
eua_clean=eua_clean.isnull().sum()
eua_clean

host_listings_count      0
latitude                 0
longitude                0
accommodates             0
bathrooms                0
                        ..
calendar_last_scraped    0
first_review             0
last_review              0
license                  0
instant_bookable         0
Length: 75, dtype: int64

In [31]:
#Convertir DataFrame a CSV
eua_clean.to_csv("California_EUA_clean.csv")
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("California_EUA_clean.csv")